In [14]:
import pandas as pd
import matplotlib.pyplot as plt

In [10]:
classificacaoGeral = pd.DataFrame({
    '': list(range(1,21)),
    'Clube': ['Botafogo','Palmeiras','Flamengo','Fortaleza','Internacional','São Paulo','Corinthians','Bahia','Cruzeiro','Vasco','Vitoria','Atletico-MG','Fluminense','Gremio','Juventude','Bragantino','Athletico-PR','Criciuma','Atletico-Go','Cuiaba'],
    'Pts':[79,73,70,68,65,59,56,53,52,50,47,47,46,45,45,44,42,38,30,30],
    'PJ': [38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38],
    'Vit': [23,22,20,19,18,17,15,15,14,14,13,11,12,12,11,10,11,9,7,6],
    'E': [10,7,10,11,11,8,11,8,10,8,8,14,10,9,12,14,9,11,9,12],
    'DER': [5,9,8,8,9,13,12,15,14,16,17,13,16,17,15,14,18,18,22,20],
    'GM': [59,60,61,53,53,53,54,49,43,43,45,47,33,44,48,44,40,42,29,29],
    'GC': [29,33,45,39,36,43,45,49,41,56,52,54,39,50,59,48,46,61,58,49],
    'SG': [30,27,19,14,17,10,9,0,2,-13,-7,-7,-6,-6,-11,-4,-6,-19,-29,-20]
})

In [15]:
classificacaoGeral.style.hide(axis="index")